### PR TITLE
Use sparql instead

### LINKED ISSUE #33: iTQL is dead, use Sparql instead
We've moved to using an external Blazegraph triplestore and the Smithsonian's trippi-sparql connector. Unfortunately this only allows us to use Sparql queries. 
Therefore queries [like this](https://github.com/mjordan/islandora_context/blob/ba7cf36d9696c0402a86a15dfafa3ce4008b3f4e/plugins/islandora_context_condition_collection_member.inc#L95) cause Exceptions and these occur even when the context you are accessing is not using the plugin.
I had to uninstall islandora_context to edit an existing context that was just using Path.

### PR DESCRIPTION
**Pull request by whikloj**
Resolves #33

### CODE REVIEW

**Comment by mjordan** [comment]
@whikloj I don't have time to test this, but I'm happy to merge it now anyway, if you think that it will work on Mulgara (so as to preserve sideways (?) compatibility). What do you think?

**Comment by mjordan** [comment]
I can look into why that plugin is being run when it isn't active later.

**Comment by whikloj** [comment]
Actually hang on, these won't work. I left some iTQL in there. More commits coming.

**Comment by mjordan** [comment]
I commented back on the issue, but maybe we can eliminate that custom query by replacing it with https://github.com/Islandora/islandora_solution_pack_collection/blob/7.x/includes/utilities.inc#L210, at the risk of introducing a dependency on the Collection SP.

**Comment by mjordan** [comment]
Thanks for the fix @whikloj!

**Pull request merged**
